# Use the official PostgreSQL image
FROM postgres:latest

# Default environment variables
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase
ENV PGPORT=5433

# Expose new port
EXPOSE ${PGPORT}
