spring:
  application:
    name: product-management

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port : 8081

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE}
  queue:
    name: ${RABBITMQ_QUEUE}
  routing:
    key: ${RABBITMQ_ROUTING_KEY}

queries:
  product:
    get_all: "SELECT * FROM product"
    get_by_id: "SELECT * FROM product WHERE id = ?"
    get_by_name: "SELECT * FROM product WHERE name = ?"
    create: "INSERT INTO product (name, description, price, expiration_date) VALUES (?, ?, ?, ?)"
    delete: "DELETE FROM product WHERE id = ?"

