spring:
  application:
    name: product-management

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: guest
    password: guest

server:
  port : 8080

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE}
  queue:
    name: ${RABBITMQ_QUEUE}
  routing:
    key: ${RABBITMQ_ROUTING_KEY}
